// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN_DrEXGMUkovdkTEOtB8Ju8DMzpehdTA',
    appId: '1:153020794630:web:52d745c5af90956a210087',
    messagingSenderId: '153020794630',
    projectId: 'kloth-venom',
    authDomain: 'kloth-venom.firebaseapp.com',
    storageBucket: 'kloth-venom.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2O8hXw08xErH4UgTQ_pgPE92kkto-604',
    appId: '1:153020794630:android:7f53ee91b9cd03bc210087',
    messagingSenderId: '153020794630',
    projectId: 'kloth-venom',
    storageBucket: 'kloth-venom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu2lFtR9YVnfAejmvu5WLjScHUR2RZ5yc',
    appId: '1:153020794630:ios:b6f6d0e10ca9f85f210087',
    messagingSenderId: '153020794630',
    projectId: 'kloth-venom',
    storageBucket: 'kloth-venom.appspot.com',
    iosClientId: '153020794630-pmodj43j71cves83flv4kuqsulff0isn.apps.googleusercontent.com',
    iosBundleId: 'com.example.kloth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu2lFtR9YVnfAejmvu5WLjScHUR2RZ5yc',
    appId: '1:153020794630:ios:7cccacadd6d48c9e210087',
    messagingSenderId: '153020794630',
    projectId: 'kloth-venom',
    storageBucket: 'kloth-venom.appspot.com',
    iosClientId: '153020794630-gf8ukne78th3ucr1dq4ne1g5nainv3kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.kloth.RunnerTests',
  );
}
